package com.fleet.gpstracker.email;

import com.fleet.gpstracker.models.GpsLocation;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 * Email template generator for GPS location updates
 */
public class EmailTemplate {

    /**
     * Generate email subject
     */
    public static String generateSubject(GpsLocation location) {
        return String.format("GPS Update - %s - %s",
                           location.getDeviceSerial(),
                           new SimpleDateFormat("HH:mm", Locale.getDefault())
                               .format(location.getReceivedAt()));
    }

    /**
     * Generate email body (HTML format)
     */
    public static String generateBody(GpsLocation location) {
        SimpleDateFormat dateFormat = new SimpleDateFormat(
            "yyyy-MM-dd HH:mm:ss", Locale.getDefault());

        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>");
        html.append("<html><head>");
        html.append("<style>");
        html.append("body { font-family: Arial, sans-serif; margin: 20px; }");
        html.append("table { border-collapse: collapse; width: 100%; max-width: 600px; }");
        html.append("th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }");
        html.append("th { background-color: #4CAF50; color: white; }");
        html.append("tr:nth-child(even) { background-color: #f2f2f2; }");
        html.append(".map-link { display: inline-block; margin: 15px 0; padding: 10px 20px; ");
        html.append("background-color: #4CAF50; color: white; text-decoration: none; ");
        html.append("border-radius: 5px; }");
        html.append(".map-link:hover { background-color: #45a049; }");
        html.append("</style>");
        html.append("</head><body>");

        html.append("<h2>GPS Location Update</h2>");

        html.append("<table>");
        html.append("<tr><th>Field</th><th>Value</th></tr>");
        html.append(String.format("<tr><td>Device</td><td>%s</td></tr>",
                                 location.getDeviceSerial()));
        html.append(String.format("<tr><td>Latitude</td><td>%.6f</td></tr>",
                                 location.getLatitude()));
        html.append(String.format("<tr><td>Longitude</td><td>%.6f</td></tr>",
                                 location.getLongitude()));
        html.append(String.format("<tr><td>Heading</td><td>%s</td></tr>",
                                 location.getFormattedHeading()));
        html.append(String.format("<tr><td>Timestamp</td><td>%s</td></tr>",
                                 location.getTimestamp()));
        html.append(String.format("<tr><td>Received</td><td>%s</td></tr>",
                                 dateFormat.format(location.getReceivedAt())));
        html.append("</table>");

        html.append("<br>");
        html.append(String.format("<a class='map-link' href='%s' target='_blank'>View on Google Maps</a>",
                                 location.getGoogleMapsUrl()));

        html.append("<br><br>");
        html.append("<p style='color: #666; font-size: 12px;'>");
        html.append("This email was automatically generated by Fleet GPS Tracker System.<br>");
        html.append("Time sent: " + dateFormat.format(new Date()));
        html.append("</p>");

        html.append("</body></html>");

        return html.toString();
    }

    /**
     * Generate simple text body (fallback)
     */
    public static String generateTextBody(GpsLocation location) {
        SimpleDateFormat dateFormat = new SimpleDateFormat(
            "yyyy-MM-dd HH:mm:ss", Locale.getDefault());

        StringBuilder text = new StringBuilder();
        text.append("GPS Location Update\n");
        text.append("===================\n\n");
        text.append("Device: ").append(location.getDeviceSerial()).append("\n");
        text.append("Latitude: ").append(location.getLatitude()).append("\n");
        text.append("Longitude: ").append(location.getLongitude()).append("\n");
        text.append("Heading: ").append(location.getFormattedHeading()).append("\n");
        text.append("Timestamp: ").append(location.getTimestamp()).append("\n");
        text.append("Received: ").append(dateFormat.format(location.getReceivedAt())).append("\n\n");
        text.append("Google Maps: ").append(location.getGoogleMapsUrl()).append("\n\n");
        text.append("---\n");
        text.append("Fleet GPS Tracker System\n");
        text.append("Time sent: ").append(dateFormat.format(new Date())).append("\n");

        return text.toString();
    }
}
